# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
# Zephyr 4.1 Update - Board Revisions
# As part of this change, ZMK is now using board/shield revisions, rather than duplicate
# board/shield definitions. This means that instead of having e.g. nice_nano, and nice_nano_v2,
# we only have nice_nano, which by default points to the 2.0.0 revision. To point to the
# original Nice!Nano V1, you would need to use nice_nano@1.0.0 where you would have previously
# used nice_nano. Of course, you could also put nice_nano@2.0.0 if you wished to make that
# explicit, instead of merely replacing nice_nano_v2 with nice_nano. 
#
---
include:
  - board: nice_nano
    shield: corne_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: corne_right
